// <auto-generated />
namespace USIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_email_students : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_email_students));
        
        string IMigrationMetadata.Id
        {
            get { return "202005231333021_added_email_students"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
