// <auto-generated />
namespace USIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class courses_added_year_semester_columns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(courses_added_year_semester_columns));
        
        string IMigrationMetadata.Id
        {
            get { return "202005202354140_courses_added_year_semester_columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
